version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gmoms-server
    hostname: gmoms-server
    ports:
      - 9090:9090
    deploy:
      restart_policy:
        condition: on-failure
